name: Build

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build-win
      - run: |
          mkdir artifact
          xcopy dist\*.exe artifact\ /Y
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: windows-build
          path: artifact
